name: Docs

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create build environment
      working-directory: docs
      run: mkdir build

    - name: Update version
      working-directory: docs
      run: python update_version.py

    - name: Run doxygen
      uses: mattnotmitt/doxygen-action@v1
      with:
        working-directory: 'docs/source/'

    - name: Build docs
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
        
    - name: Create artifact
      uses: actions/upload-artifact@v2
      with:
        name: DocumentationHTML
        path: docs/build/html/

  # Publish built docs to gh-pages branch.
  publish:
    runs-on: ubuntu-latest
    needs: build
    # Runs if push to master
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    
    steps:
    - name: Clone gh-pages
      run: | 
        git clone https://github.com/gavrilikhin-d/libos --branch gh-pages --single-branch gh-pages
        cd gh-pages
        touch .nojekyll
    
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: DocumentationHTML
        path: gh-pages
    
    - name: Commit changes
      working-directory: gh-pages
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true
        # The above command will fail if no changes were present, ignore it.

    - name: Push commit
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
